name: Build

on:
  push:
    # master branch already handles building on itself
    branches-ignore: ["master"]
  pull_request:
  workflow_call:

jobs:
  build:
    name: Check types and build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: pnpm run build
